name: learn-github-actions
on: [push]
jobs:
  print-basic-information:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git branch
      - run: git rev-parse HEAD
      - run: ls -alr
      - run: exit 1
