name: learn-github-actions
on:
  push:
    paths: "website/**"

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cp -r website/public/** docs
          git add docs/*
          git checkout production
          git commit -am"release website"
          git push
