name: learn-github-actions
on:
  push:
    paths: "desktop-app/src/**.tsx"

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: desktop-app/package-lock.json
      - run: |
          cd desktop-app
          npm ci
          npm test
